### ISSUE TITLE
how to export resource using  with gantt chart to excel?

### ISSUE THREAD

**Issue by Anda001** [PopovGP/Export-MS-Project-to-MS-Excel#1]
rt

**Comment by PopovGP** [comment]
This module exports column "Resouce names". If it is filled in your MS Project file, it will be exported.

**Comment by Anda001** [comment]
yes. but we want to seperate each human resource to see their task load. I'm trying to modify your script.

**Comment by PopovGP** [comment]
Could you describe how it should look like? You may draw some sample by hand.

**Comment by Anda001** [comment]
![image](https://user-images.githubusercontent.com/1329895/104432359-eaba6580-55c3-11eb-8b77-e732dec98dda.png)
sth like this.
I generated the image use your script,and manually modified some items.

**Comment by PopovGP** [comment]
PersonB is working on several projects, which are in separate files? 
ProjectDetail is a task name?

**Comment by Anda001** [comment]
No. ProjectA and ProjectB are the  top level projects. ProjectDetails are the  second level projects.
They are all in the same file. I use the sub level projects  to show project  milestone.

**Comment by Anda001** [comment]
which I want to implement is sth like the  "Resource Using View",but use gantt chart instead of the the right part of the view,
and export to excel.

**Comment by PopovGP** [comment]
I understand now how it should look like. Sorry, at present it's not implemented and you should try do it yourself.
I can do it, but later.

**Comment by Anda001** [comment]
OK.I'm trying now.

**Comment by mhykol2k** [comment]
@wuzhenda Did you get this sorted, we are having the same issue

**Comment by Anda001** [comment]
> @wuzhenda Did you get this sorted, we are having the same issue

yes,I modified and fit my needs.
[https://github.com/wuzhenda/Export-MS-Project-to-MS-Excel](https://github.com/wuzhenda/Export-MS-Project-to-MS-Excel)

but since two years passed and this repo has added some commits, sth maybe tested again.
