### ISSUE TITLE
Option to change gantt view from weekly to monthly or quarterly etc

### ISSUE THREAD

**Issue by rcowen1977** [PopovGP/Export-MS-Project-to-MS-Excel#7]
It would be excellent if the user could select the period for the gnatt view from being weekly to Monthly, quarterly etc.

**Comment by PopovGP** [comment]
> It would be excellent if the user could select the period for the gnatt view from being weekly to Monthly, quarterly etc.

Do you need this feature? Can you give sample project file?

**Comment by rcowen1977** [comment]
It would be good to have.  I create a Programme plan by linking a number of subprojects together.  We have to provide a Plan on a page but when we are not baseline this can change on a regular basis.  it would fantastic to see the programme by month.  It would save me hours of work each month.  I can provide a set of plans so you can see the type of thing I'm talking about if needed.

**Comment by PopovGP** [comment]
> It would be good to have. I create a Programme plan by linking a number of subprojects together. We have to provide a Plan on a page but when we are not baseline this can change on a regular basis. it would fantastic to see the programme by month. It would save me hours of work each month. I can provide a set of plans so you can see the type of thing I'm talking about if needed.

Yes, please, give some plans to understand the result.

**Comment by rcowen1977** [comment]
[examplePlans.zip](https://github.com/PopovGP/Export-MS-Project-to-MS-Excel/files/8034981/examplePlans.zip)
![POAP](https://user-images.githubusercontent.com/99347077/153259172-04a80811-81ae-42bf-922c-07e3c7fa7eae.jpg)

The bottom section of the image is what I am trying to achieve with the Gantt by month

**Comment by PopovGP** [comment]
Got it, thanks!

**Comment by rcowen1977** [comment]
is this amendment possible?

**Comment by reza2511** [comment]
Hi @PopovGP 

Have you had any luck finding a solution?

Kind regards

**Comment by rcowen1977** [comment]
Hi, Sadly not. 

R

**Comment by PopovGP** [comment]
> Hi, Sadly not.
> 
> R

Hello! Is it still needed?

**Comment by reza2511** [comment]
> > Hi, Sadly not.
> > R
> 
> Hello! Is it still needed?

We really desperately need it. Any help would be greatly appreciated.

Kind regards

**Comment by rcowen1977** [comment]
Hi, Yes it's still needed.

**Comment by reza2511** [comment]
This is just an example of Monthly Timescale GanttChart

![image](https://user-images.githubusercontent.com/128479780/226624845-d79181e0-2cee-4ccd-8c78-d91045a5d7e5.png)

**Comment by PopovGP** [comment]
Ok, I will do it.

**Comment by PopovGP** [comment]
Hi everyone!
Added precedure to export Gantt chart in months, please give a try

**Comment by reza2511** [comment]
@PopovGP I appreciate all the help you've provided. Your hard work and dedication have been invaluable. Thank you so much and I wish all the best.

SAMPLE: 

MONTHLY: 

![image](https://user-images.githubusercontent.com/128479780/229224933-b65e3e9a-a3b7-4cb6-b6e1-a72a8fe0a7d0.png)

DAILY:

![image](https://user-images.githubusercontent.com/128479780/229224812-83c0ff60-69fc-48f7-b782-8b197493caf8.png)

**Comment by NargesNAAM** [comment]
Thanks, you answered all my questions about the [Gantt chart](https://consultleopard.com/how-to-display-4-baselines-on-the-gantt-chart-in-primavera-p6/).
