### ISSUE TITLE
how export more task fields?

### ISSUE THREAD

**Issue by weituo2002** [PopovGP/Export-MS-Project-to-MS-Excel#8]
MS Project task have customized fields, how export them?

**Comment by PopovGP** [comment]
You mean "Text1..30", "Number1..30"?

**Comment by weituo2002** [comment]
for example, MS Project have many custom fields for task, I may define a task field named “responsible department ”，I wish to export this task with that field "responsible department" to excel sheet as a colum

**Comment by weituo2002** [comment]
That is, more fields except fix fields:
Exports task filelds:
№
Unique task ID
Task name
Task start date
Task end datae
Duration
Resource names
Task predecessors
% complete

**responsible department
Department of collaboration**

and so on

**Comment by PopovGP** [comment]
All customized fields are like any other fields.
Made some examples how to do it (see pictures).

![01_Choosing_field](https://user-images.githubusercontent.com/59528040/198827983-363d915b-73e9-480b-82bc-49e4d152cfad.jpg)
![02_FieldRenamed_founding_field_ID](https://user-images.githubusercontent.com/59528040/198827984-aad41729-9c51-455c-94c4-b9fb8ecc8809.jpg)
![03_PreparedProject](https://user-images.githubusercontent.com/59528040/198827985-08bb73bf-9204-4970-9d58-e146521a338b.jpg)
![04_StartVBACoding](https://user-images.githubusercontent.com/59528040/198827986-fce7a79d-f43e-4e33-bc72-f8aa8d694d78.jpg)
![05_VBACode](https://user-images.githubusercontent.com/59528040/198827987-f28b7af2-8525-4a70-90ca-4d95e9449d98.jpg)
![06_ResultExport](https://user-images.githubusercontent.com/59528040/198827982-f01a2461-ef85-4cd6-b6db-06a38956830d.jpg)
